name = "boring-sales-growth"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-06-30"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vercel/output/static"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]